name: Nightly

on:
  workflow_dispatch: # To Generate wheels on demand outside of schedule.
  schedule:
    - cron: '0 3 * * *' # run at 3 AM UTC / 8 PM PDT

permissions:
  contents: read

jobs:
  run-test-for-nightly:
    uses: ./.github/workflows/actions.yml
  nightly:
    name: Build Wheel file and upload
    needs: [run-test-for-nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip setuptools
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: pip cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install twine
          pip install -r requirements.txt --progress-bar off
      - name: Build wheel file
        run: |
          python pip_build.py --nightly
      - name: Publish KerasRS Nightly to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_NIGHTLY_API_TOKEN }}
          verbose: true
